name: xcodebuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, reopened, ready_for_review]
  schedule:
    - cron: "0 5 1 * *"

env:
  PROJECT: Brief.xcodeproj
  SCHEME: Brief
  DESTINATION: platform=OS X

jobs:
  build-app:
    name: Build Brief app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0]
    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION"
  test-app:
    name: Test Brief app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0]
    steps:
    - uses: actions/checkout@v2
    - name: Test App
      run: xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" test
